#:schema node_modules/wrangler/config-schema.json
name = "bolt"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-03-28"
pages_build_output_dir = "./build/client"
send_metrics = false

[build]
command = "node --max-old-space-size=2048 ./node_modules/.bin/remix vite:build"
cwd = "./"
watch_dir = "./app"
